name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: esromneb/arduino:1

    steps:
    - uses: actions/checkout@v3
        with:
          submodules: recursive
    - name: compile test
      run: mkdir -p test/build && cd test/build && cmake ..
    - name: run test
      run: cd test/build && ./test
    - name: compile target
      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
